services:
  - type: web
    name: backend
    env: docker
    repo: https://github.com/oksanabaza/setu-final-project
    region: frankfurt
    plan: free
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: postgresql://oksana:7Y0EBSU8IsRdXrSZ0lvq2NmteLTVpYW0@dpg-cvuk48uuk2gs738emk40-a.oregon-postgres.render.com/scrapetrack
        fromDatabase:
          name: /scrapetrack
          property: connectionString
